[build]
builder = "dockerfile"

[deploy]
startCommand = "php artisan config:clear; php artisan config:cache; php artisan migrate --force; php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
